# Generated by Django 4.0.5 on 2022-06-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0005_image_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='preference',
            name='post',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
