# Generated by Django 4.0.5 on 2022-06-05 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clone', '0006_alter_preference_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(related_name='image_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
