# Generated by Django 4.0.5 on 2022-06-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0014_alter_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
