# Generated by Django 4.0.5 on 2022-06-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0019_remove_profile_last_name_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
