# Generated by Django 4.0.5 on 2022-06-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0020_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
